name = "bookers"

[http]
  port = "8080"
  swagger_path = ""

[env]
  [env.postgres_dsn]
    value = "postgres://diploma:@localhost:5432/diploma?sslmode=disable"
  [env.s3_endpoint]
    value = "https://hb.kz-ast.vkcs.cloud"
  [env.s3_bucket]
    value = "bookers-images"
  [env.s3_access_key]
    value = "access-key"
  [env.s3_secret_key]
    value = "secret-key"
  [env.api_key]
    value = "api-key
    